Process only one bag at a time, break out packaging service
RockefellerArchiveCenter/zorya pull request #97
Opened 2021-11-03 21:57 UTC by bonniegee

This needs some additional work, but wanted to push up a draft because I'd like feedback on the following:

* I decided to not go with the base routine approach, since the first two routines would not use it (they do not start by looking at what's in the database). However, I may be overthinking it?
* I was struggling with tests for the new service, because getting the database helper to line up with my fixture was a pain. I was not sure if now would be a good time to implement database fixtures, or work with what I have and file an issue?

2021-11-04 13:16 UTC, helrond commented
Took a quick look at this.
- I think I would suggest implementing a base routine class. Even if the Download and Discover routines aren't based on this class there are still four others where you could factor out some common logic. Pushing it even further, it would be possible to implement a `get_object` (or similarly named) method on your base class which would return the object that should be acted on. I'm not convinced it's necessary to go there right now because it would prevent you from factoring out some of the things like setting process_status, etc.
- Yeah to me the fact that you were struggling to get the database into the right state indicates that the time is right for moving to fixtures. That will probably require breaking the tests apart a bit so that each routine has it's own TestCase class. But I think you could pretty easily produce those fixtures by using the existing `add_bags_to_db` method and then the `dumpdata` management command.
- Last, minor point, but I think it makes sense to move the fixture directory inside the `package_bag` app, since that's where Django is looking for it by default.

2021-11-04 19:38 UTC, bonniegee commented
Fixes #95, fixes #94

Also adds a BaseRoutine for most of the services, and adds database fixtures to tests

2021-11-04 21:12 UTC, helrond requested changes
A few very very minor things. Overall looks great!

2021-11-04 21:12 UTC, helrond commented on package_bag/routines.py
> +        msg = "Files downloaded." if list_to_download else "No files ready to be downloaded."
```suggestion
        msg = "File downloaded." if list_to_download else "No files ready to be downloaded."
```

2021-11-04 21:12 UTC, helrond commented on package_bag/routines.py
>  # how does something get sent from one bag to another? how does batching work?
This comment can be deleted, right?

2021-11-04 21:12 UTC, helrond commented on package_bag/routines.py
> +    idle_message = "No bags to assign rights to found."
```suggestion
    idle_message = "No bags waiting for rights assignment."
```

2021-11-04 21:12 UTC, helrond commented on package_bag/routines.py
> +        bag.rights_data = rights_json
```suggestion
        bag.rights_data = self.retrieve_rights(bag)
```

2021-11-04 21:12 UTC, helrond commented on package_bag/tests.py
> +                'http://aquila-web:8000/rights',
I think it might make sense to use a config value here (since that's where this should be coming from) rather than hardcoding a value?

2021-11-04 21:12 UTC, helrond commented on package_bag/tests.py
> +            len(listdir(settings.DEST_DIR)), 3,
I'm seeing you assert on the number 3 a lot - wondering if there's a way you can set a variable for this (either globally or in each test) so it's a bit more obvious what this is asserting against?

2021-11-05 13:36 UTC, bonniegee commented
I made those changes BUT now tests are failing for the RightsAssigner due to it checking for today's date for `end_date`. That's as far as I've gotten so far--since this app isn't actually calculating anything this is likely an issue with the tests?

2021-11-05 14:01 UTC, helrond commented
Yup - it looks like your db fixture has an `end_date` of 2021-11-04 but your `END_DATE` helper has a dynamic date of whatever today is. I think you want to change that helper to be a static value?

2021-11-05 14:59 UTC, helrond approved these changes

2021-11-05 15:20 UTC, merged